spring:
  application:
    name: learn-graphql-java

server:
  http2:
    enabled: true

graphql:
  servlet:
    exception-handlers-enabled: true
    tracing-enabled: true
  playground:
    enabled: true
    tabs:
      - name: Bank Account query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
    headers:
      "user_id": "test-user-id"
logging:
  pattern:
    # the value grabbed from the logging/logback/defaults.xml CONSOLE_LOG_PATTERN
    console: -%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
