spring:
  application:
    name: learn-graphql-java

server:
  http2:
    enabled: true

graphql:
  servlet:
    exception-handlers-enabled: true
  playground:
    enabled: true
    tabs:
      - name: Bank Account query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
    headers:
      "user_id": "test-user-id"
